import SystemSelect from '@/Components/SystemSelect';
import DataTable from '@/Components/DataTable';
import RecognitionNominationForm from '@/Components/Recognition/RecognitionNominationForm';
import StatCard from '@/Components/StatCard';
import AuthenticatedLayout, { HeaderActions, HeaderFilters } from '@/Layouts/AuthenticatedLayout';
import { recognitionClient, recognitionError } from '@/data/recognitionClient';
import { RECOGNITION_USER_WORKSPACES, denseRank, leaderboardForPeriod, normalizeRecognitionState, ownRecognitions, ownSubmissions, publicFeed, type RecognitionPeriod, type RecognitionRecord, type RecognitionState } from '@/data/recognition';
import { useHashWorkspace } from '@/workspaceNavigation';
import { Head } from '@inertiajs/react';
import { Award, Eye, Medal, Plus, Send, Trophy, UserRoundCheck, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Props = { initialRecognitionState?: unknown };
const primary = 'inline-flex h-9 items-center justify-center gap-2 rounded-lg bg-[#F4B400] px-4 text-xs font-bold text-black transition hover:bg-[#dca300]';
const formatDate = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString('en-PH', { year: 'numeric', month: 'short', day: 'numeric' }) : '—';
function statusClass(status: string): string { return status === 'Recognized' ? 'bg-emerald-100 text-emerald-700' : status === 'Pending Review' ? 'bg-amber-100 text-amber-800' : status === 'Draft' ? 'bg-slate-200 text-slate-700' : 'bg-rose-100 text-rose-700'; }
function initialState(value: unknown): RecognitionState | null { try { return value ? normalizeRecognitionState(value) : null; } catch { return null; } }

function PublicDetails({ record, onClose }: { record: RecognitionRecord; onClose: () => void }) {
    return <div className="fixed inset-0 z-[100] flex justify-end bg-slate-950/60 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside role="dialog" aria-modal="true" aria-label={`${record.recipient.name} recognition details`} className="flex h-full w-full max-w-2xl flex-col bg-slate-50 shadow-2xl animate-in slide-in-from-right duration-200"><div className="flex items-start justify-between bg-slate-950 p-6 text-white"><div><span className="rounded-full bg-amber-400/20 px-2.5 py-1 text-xs font-bold text-amber-300">{record.category?.name || 'Recognition'}</span><h2 className="mt-3 text-xl font-bold">{record.recipient.name}</h2><p className="text-sm text-white/60">{record.recipient.position || 'Unassigned'} · {record.recipient.department || 'Unassigned'}</p></div><button onClick={onClose} aria-label="Close details"><X className="h-5 w-5 text-white/60" /></button></div><div className="min-h-0 flex-1 space-y-4 overflow-y-auto p-6"><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Recognized achievement</p><h3 className="mt-2 font-bold text-slate-950">{record.title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{record.achievementDetails}</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-400">Nominated by</p><p className="mt-1 text-sm font-bold text-slate-800">{record.nominator.name}</p></div><div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-400">Recognized</p><p className="mt-1 text-sm font-bold text-slate-800">{formatDate(record.recognizedAt)}</p></div></div><p className="rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-900">Recognition is an official social-recognition record. It is not a certificate or an automatic Performance, Competency, or Succession score.</p></div><div className="flex justify-end border-t border-slate-200 bg-white px-6 py-4"><button className="h-9 rounded-lg border border-slate-300 bg-white px-4 text-xs font-bold text-slate-700" onClick={onClose}>Close</button></div></aside></div>;
}

function Feed({ records, onSelect }: { records: RecognitionRecord[]; onSelect: (record: RecognitionRecord) => void }) {
    if (records.length === 0) return <div className="app-card p-12 text-center"><Award className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 text-sm font-bold text-slate-700">No published recognition yet</p><p className="mt-1 text-xs text-slate-400">Approved recognition will appear here.</p></div>;
    return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{records.map((record) => <button key={record.id} onClick={() => onSelect(record)} className="app-card p-5 text-left transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-600"><Award className="h-5 w-5" /></div><span className="rounded-full bg-amber-100 px-2 py-1 text-[11px] font-bold text-amber-800">{record.category?.name || 'Recognition'}</span></div><h3 className="mt-4 text-base font-bold text-slate-950">{record.recipient.name}</h3><p className="text-xs text-slate-400">{record.recipient.position} · {record.recipient.department}</p><p className="mt-3 line-clamp-2 text-sm font-semibold text-slate-700">{record.title}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-xs text-slate-400"><span>by {record.nominator.name}</span><span>{formatDate(record.recognizedAt)}</span></div></button>)}</div>;
}

export default function UserRecognition({ initialRecognitionState }: Props) {
    const [workspace, setWorkspace] = useHashWorkspace(RECOGNITION_USER_WORKSPACES, 'Recognition Feed');
    const [state, setState] = useState<RecognitionState | null>(() => initialState(initialRecognitionState));
    const [loading, setLoading] = useState(!state); const [error, setError] = useState(''); const [selected, setSelected] = useState<RecognitionRecord | null>(null); const [busyId, setBusyId] = useState<string | null>(null);
    const [leaderboardPeriod, setLeaderboardPeriod] = useState<RecognitionPeriod>('All Time');
    const periodLeaderboard = useMemo(() => leaderboardForPeriod(state?.records ?? [], leaderboardPeriod), [state, leaderboardPeriod]);
    async function reload() { setLoading(true); setError(''); try { setState(await recognitionClient.state()); } catch (requestError) { setError(recognitionError(requestError)); } finally { setLoading(false); } }
    useEffect(() => { if (!state) void reload(); }, []);
    async function submitDraft(record: RecognitionRecord) { setBusyId(record.id); setError(''); try { await recognitionClient.submit(record.id); await reload(); } catch (requestError) { setError(recognitionError(requestError)); } finally { setBusyId(null); } }
    if (!state) return <AuthenticatedLayout header={<h1 className="text-lg font-bold">Recognition</h1>}><Head title="Recognition" /><div className="p-6"><div className="app-card p-10 text-center text-sm text-slate-500">{loading ? 'Loading Recognition…' : error || 'Recognition state is unavailable.'}</div></div></AuthenticatedLayout>;
    const feed = publicFeed(state); const mine = ownRecognitions(state); const submissions = ownSubmissions(state);
    const recordTable = (records: RecognitionRecord[], title: string, submissionsView = false) => <DataTable title={title} data={records} rowKey={(record) => record.id} onRowClick={setSelected} columns={[
        { key: 'recipient', header: submissionsView ? 'Recipient' : 'Recognition', render: (record) => <div><p className="font-bold text-slate-900">{submissionsView ? record.recipient.name : record.title}</p><p className="text-xs text-slate-400">{record.recipient.position} · {record.recipient.department}</p></div> },
        { key: 'category', header: 'Category', render: (record) => record.category?.name || '—' },
        { key: 'date', header: 'Achievement Date', render: (record) => formatDate(record.achievementDate) },
        { key: 'status', header: 'Status', render: (record) => <span className={`rounded-full px-2 py-1 text-xs font-bold ${statusClass(record.status)}`}>{record.status}</span> },
        { key: 'action', header: 'Action', render: (record) => submissionsView && record.status === 'Draft' ? <button disabled={busyId === record.id} onClick={(event) => { event.stopPropagation(); void submitDraft(record); }} className="inline-flex items-center gap-1 rounded-lg bg-[#F4B400] px-3 py-1.5 text-xs font-bold text-black disabled:opacity-50"><Send className="h-3.5 w-3.5" />Submit</button> : <Eye className="h-4 w-4 text-slate-500" /> },
    ]} />;
    return <AuthenticatedLayout header={<h1 className="text-lg font-bold text-slate-950">Recognition</h1>}><Head title="Recognition" /><HeaderActions>{workspace !== 'Nominate a Colleague' && <button className={primary} onClick={() => { window.location.hash = '#Nominate%20a%20Colleague'; }}><Plus className="h-4 w-4" />Nominate a Colleague</button>}</HeaderActions>{workspace === 'Company Leaderboard' && <HeaderFilters><SystemSelect aria-label="Leaderboard period" value={leaderboardPeriod} onChange={(event) => setLeaderboardPeriod(event.target.value as RecognitionPeriod)}>{['All Time','This Month','This Quarter','This Year'].map((value) => <option key={value}>{value}</option>)}</SystemSelect></HeaderFilters>}{selected && <PublicDetails record={selected} onClose={() => setSelected(null)} />}<div className="space-y-4 p-5">{error && <div className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}<div className="grid gap-3 sm:grid-cols-3"><StatCard icon={Trophy} label="Company Recognitions" value={state.metrics.recognized} onClick={() => setWorkspace('Recognition Feed')} /><StatCard icon={UserRoundCheck} label="People Recognized" value={state.metrics.peopleRecognized} onClick={() => setWorkspace('Company Leaderboard')} /><StatCard icon={Medal} label="My Recognitions" value={mine.length} onClick={() => setWorkspace('My Recognitions')} /></div>
        {workspace === 'Recognition Feed' && <Feed records={feed} onSelect={setSelected} />}
        {workspace === 'Company Leaderboard' && <><div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-900">Transparent approved-recognition counts only. Ties share a rank, there are no hidden points, and this ranking does not change Performance ratings.</div><DataTable title="Company Recognition Leaderboard" data={periodLeaderboard} rowKey={(row) => row.personnelKey} columns={[{ key: 'rank', header: 'Rank', render: (row) => <span className="font-bold text-slate-900">#{denseRank(periodLeaderboard, row)}</span> },{ key: 'person', header: 'Person', render: (row) => <div><p className="font-bold text-slate-900">{row.name}</p><p className="text-xs text-slate-400">{row.position} · {row.department}</p></div> },{ key: 'count', header: 'Published Recognition', render: (row) => <strong>{row.count}</strong> },{ key: 'latest', header: 'Latest', render: (row) => formatDate(row.latestRecognizedAt) }]} /></>}
        {workspace === 'My Recognitions' && recordTable(mine, 'My Published Recognitions')}
        {workspace === 'Nominate a Colleague' && <RecognitionNominationForm state={state} embedded onSaved={reload} />}
        {workspace === 'My Submissions' && recordTable(submissions, 'My Submitted Nominations', true)}
    </div></AuthenticatedLayout>;
}
