<?php

namespace App\Http\Controllers;

use App\Models\SystemSetting;
use App\Services\Reporting\CrossModuleReportService;
use App\Services\Reporting\ReportFileExporter;
use App\Support\ReadModelCache;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ReportsStateController extends Controller
{
    public function __construct(
        private readonly CrossModuleReportService $reports,
        private readonly ReportFileExporter $files,
    ) {}

    public function show(Request $request): JsonResponse
    {
        $filters = $this->filters($request);
        $data = ReadModelCache::rememberRequest(
            'reports',
            $request->user(),
            $request,
            fn (): array => $this->reports->state($request->user(), $filters),
            $filters,
        );

        return response()->json(['data' => $data]);
    }

    public function export(Request $request, string $report, string $format): Response
    {
        abort_unless(in_array($format, ['csv', 'xlsx', 'excel', 'json', 'pdf', 'print'], true), 404);
        $format = $format === 'excel' ? 'xlsx' : $format;
        $filters = $this->filters($request);
        $rows = $this->reports->rows($request->user(), $report, $filters);
        $this->reports->recordExport($request->user(), $report, $format, $filters, $rows->count());

        $defaults = config('governance.settings');
        $stored = SystemSetting::query()->get()->mapWithKeys(fn (SystemSetting $setting) => [
            $setting->setting_key => $setting->value['value'] ?? null,
        ]);
        $prefix = preg_replace('/[^a-z0-9-]+/i', '-', (string) ($stored->get('reporting.filename_prefix') ?: ($defaults['reporting.filename_prefix'] ?? 'alibaton-pd')));
        $timestamp = now('Asia/Manila')->format('Ymd-His');
        $basename = trim($prefix ?: 'alibaton-pd', '-').'-'.$report.'-'.$timestamp;
        $title = CrossModuleReportService::REPORTS[$report];
        $timezone = (string) ($stored->get('organization.timezone') ?: ($defaults['organization.timezone'] ?? 'Asia/Manila'));
        $organizationName = $stored->get('organization.name') ?: ($defaults['organization.name'] ?? 'Alibaton Construction Incorporated');

        if ($format === 'json') {
            return response()->streamDownload(
                fn () => print json_encode($rows->values()->all(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE),
                $basename.'.json',
                ['Content-Type' => 'application/json; charset=UTF-8', 'X-Content-Type-Options' => 'nosniff'],
            );
        }

        if ($format === 'xlsx') {
            return response($this->files->xlsx($rows, $title), 200, [
                'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'Content-Disposition' => 'attachment; filename="'.$basename.'.xlsx"',
                'X-Content-Type-Options' => 'nosniff',
                'Cache-Control' => 'no-store, private',
            ]);
        }

        if ($format === 'pdf') {
            return response($this->files->pdf($rows, $title, [
                'Organization' => $organizationName,
                'Generated by' => $request->user()->name,
                'Generated at' => now()->timezone($timezone)->format('Y-m-d H:i:s T'),
                'Department' => $filters['department'] ?? '',
                'Date from' => $filters['date_from'] ?? '',
                'Date to' => $filters['date_to'] ?? '',
            ]), 200, [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'attachment; filename="'.$basename.'.pdf"',
                'X-Content-Type-Options' => 'nosniff',
                'Cache-Control' => 'no-store, private',
            ]);
        }

        if ($format === 'print') {
            $html = view('reports.print', [
                'title' => $title,
                'rows' => $rows,
                'organizationName' => $organizationName,
                'dateFormat' => $stored->get('organization.date_format') ?: ($defaults['organization.date_format'] ?? 'M d, Y'),
                'generatedAt' => now()->timezone($timezone),
                'generatedBy' => $request->user()->name,
            ])->render();

            return response($html, 200, [
                'Content-Type' => 'text/html; charset=UTF-8',
                'Content-Disposition' => 'inline; filename="'.$basename.'.html"',
                'X-Content-Type-Options' => 'nosniff',
                'Cache-Control' => 'no-store, private',
            ]);
        }

        return response()->streamDownload(function () use ($rows): void {
            $output = fopen('php://output', 'wb');
            $first = $rows->first();
            if ($first !== null) {
                fputcsv($output, array_keys($first), ',', '"', '');
                foreach ($rows as $row) {
                    fputcsv($output, array_map(
                        fn ($value) => is_scalar($value) || $value === null ? $value : json_encode($value, JSON_UNESCAPED_UNICODE),
                        $row,
                    ), ',', '"', '');
                }
            }
            fclose($output);
        }, $basename.'.csv', [
            'Content-Type' => 'text/csv; charset=UTF-8',
            'X-Content-Type-Options' => 'nosniff',
        ]);
    }

    private function filters(Request $request): array
    {
        return $request->validate([
            'report' => ['nullable', 'string'], 'department' => ['nullable', 'string', 'max:120'],
            'date_from' => ['nullable', 'date'], 'date_to' => ['nullable', 'date', 'after_or_equal:date_from'],
        ]);
    }
}
